### ISSUE TITLE
Aggregation needed.

### ISSUE THREAD

**Issue by kandycoder** [kandycoder/inventory#1]
The quantity column needs to be aggregated on a weekly basis.

In the destination spreadsheet, a block of columns serves to store the quantity delta for each item for a given week. When the macro imports changes to the quantity column, it should therefore also add those quantity adjustments in the appropriate column for that week (with a new column being created if needed).

---

**Background**
An existing macro already adds new item quantities from one spreadsheet to their respective in-stock quantity in another sheet to update an inventory. It scans the source sheet for new rows, and for every new row it gets the item id and quantity values from that row. The macro then looks up the item id in the destination sheet and adds the quantity to the corresponding quantity field of the destination sheet. (The destination sheet contains total items in stock.)

**Task Description**
The job is to implement the following: if the macro is run and a new week has begun, a new column is to be created in the destination sheet with a heading for that week (such as "2023-01-15"). The new column should be created before the existing logic runs. Then, logic needs to be added to add/accumulate item quantities in the weekly column similarly to how it is already being done for the total quantity in stock. When the macro is run again in the same week, no new column is created but the quantities in the column for that week are updated again. The end result is that in addition to having the total quantity in stock, there will be new columns for every week containing the quantity delta for that week.

**Comment by clankwright** [comment]
I can probably help ya out, but will need some example spreadsheets with sample (or preferably real) data.

**Comment by kandycoder** [comment]
[Example.xlsx](https://github.com/kandycoder/inventory/files/10425608/Example.xlsx)
When you add the macro, replace `<name of source spreadsheet>` and `<name of destination spreadsheet>` with Source and Destination. When you run it, you will see cells L3 and L5 get updated. To run it again, first delete column Z in the Source sheet otherwise it will skip the already-processed rows.

**Comment by clankwright** [comment]
Thanks, but can you please upload source and destination sheets with real data, including how you want the weekly data ordered. I need this to understand exactly how you want the data organized. 
Also, can you explain in more detail how the macro is used, by whom, and for what purpose? And what exactly is requested for the added functionality and why is it required?

**Comment by kandycoder** [comment]
It is a basic inventory system. You don't need to KYC me just to implement this feature.

However, your questions make me realize that rather than relying on the date when the macro is run, the Source sheet needs a date column for the script to determine which (new) weekly column in the Destination sheet to add that item quantity to, on an item-by-item basis. I have added that date column to the Example file in my comment above, and I have edited the Task Description above accordingly.

I'd love to give you 100 sats right now above the bounty just for helping find that bug in the Task Description, even if you don't want to continue working on this. Just send me an LN invoice where you want the 100 sats to go.

**Comment by clankwright** [comment]
No intent to KYC you, just trying to understand the role of end user (e.g. shelf stocker, inventory, warehouse, business owner?), so I can satisfy their requirements. Sorry, specs are still too vague for me to start work on this without more detail. Will reconsider doing it for 300k sats, once your requirements are more explicit.
